#!/bin/sh
#
# dotfile manager 1.0

# === Calculate scriptpath

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# === Functions

# collects the config and saves it near doma
collect_config() {
	echo "collect i3 conf"
	[ ! -d $SCRIPTPATH/i3 ] && mkdir $SCRIPTPATH/i3
	cp -r ~/.i3/* $SCRIPTPATH/i3/  
	echo "collect zshrc"
	cp -r ~/.zshrc $SCRIPTPATH/zshrc
	echo "collect termite conf"
	cp -r ~/.config/termite/config $SCRIPTPATH/termite.conf  
	echo "collect nvim conf"
	cp -r ~/.config/nvim/init.vim $SCRIPTPATH/init.vim
	echo "collecting vim snippets"
	cp -r ~/.config/coc/ultisnips $SCRIPTPATH/ultisnips
	echo "collect comption conf"
	cp -r ~/.config/compton.conf $SCRIPTPATH/compton.conf
	echo "collecting alias file"
	cp -r ~/.aliases $SCRIPTPATH/aliases
	echo "collecting i3status conf"
	cp -r ~/.config/i3status/config $SCRIPTPATH/i3status.conf
	echo "collecting xmouseless config"
	cp ~/.config/xmouseless/config.h $SCRIPTPATH/xmouseless.h
	echo "Finished collecting the whole config!"
}

upload_config() {
	git add .
	echo "Commit message:"
	read msg
	git commit -m "${msg}"
	git push
}

# applies confg files to its destinations
apply_config() {
	echo "apply i3 conf"
	cp -r $SCRIPTPATH/i3/* ~/.i3/
	echo "apply zshrc "
	cp -r $SCRIPTPATH/zshrc ~/.zshrc
	echo "apply termite conf"
	cp -r $SCRIPTPATH/termite.conf ~/.config/termite/config
	echo "apply nvim conf"
	cp -r $SCRIPTPATH/init.vim ~/.config/nvim/init.vim
	echo "deploying vim snippets"
	cp -r $SCRIPTPATH/ultisnips ~/.config/coc/ultisnips
	echo "apply comption conf"
	cp -r $SCRIPTPATH/compton.conf ~/.config/compton.conf
	echo "applying alias file"
	cp -r $SCRIPTPATH/aliases ~/.aliases
	echo "applying i3status conf"
	cp -r $SCRIPTPATH/i3status.conf ~/.config/i3status/config
	echo "setting up xmouseless"
	sudo rm -r ~/.config/xmouseless
	git clone https://github.com/jbensmann/xmouseless.git ~/.config/xmouseless
	cp -r $SCRIPTPATH/xmouseless.h ~/.config/xmouseless/config.h
	cd ~/.config/xmouseless/
	make
	sudo make install
	cd $SCRIPTPATH
	echo "Finished applying the whole config!"
}

if [ $# -eq 1 ]; then
	option=$1
else 

	echo "Choose Option:"
	echo "  (s)ave: Will collect all configured dotfiles from filesystem."
	echo "  (u)pload: Will upload the dotfiles to the git server defined in git
repo settings"
	echo "  (a)pply: Will apply all config files in from this collection to the right places."

	read option
	echo ""
fi

if [ "$option" = "s" ]; then
	echo "Start collecting configs"
	collect_config
elif [ "$option" = "a" ]; then
	echo "Start applying configs"
	apply_config
elif [ "$option" = "u" ]; then
	echo "Starting upload"
	upload_config
	echo "Not an option"
fi

