#!/bin/bash

newSink=`pactl list short sinks | grep IDLE | cut -c 1`
if [ -z $newSink ]
then
    newSink=`pactl list short sinks | grep SUSPENDED | cut -c 1`
fi

pactl list short sink-inputs|while read stream; do
    streamId=$(echo $stream|cut '-d ' -f1)
    echo "moving stream $streamId"
    pactl move-sink-input "$streamId" "$newSink"
done
